name: Python - Issue Trigger Workflow

on:
  issues:
    types: [opened, edited]

jobs:
  build-the-work-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Read issue title
        run: |
          python automation.py "${{ github.event.issue.title }}" "${{ github.event.issue.body }}"

  close-issue:
    runs-on: ubuntu-latest
    needs: build-the-work-space
    if: ${{ github.event.issue.pull_request == null }}  # Only run for issues (not PRs)
    steps:
      - name: Close issue
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              state: 'closed'
            });