name: Issue Trigger

on:
  issues:
    types: [opened, edited]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Required to close issues
      contents: read  # Required for checkout
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process issue
        run: |
          python automation.py "${{ github.event.issue.title }}" "${{ github.event.issue.body }}"

      - name: Close automated issues
        if: ${{ contains(github.event.issue.labels.*.name, 'automated') && github.event.issue.pull_request == null }}
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              state: 'closed',
              body: context.payload.issue.body + '\n\n[Automatically closed by workflow]'
            });