name: Python - Issue Trigger Workflow

on:
  push:
    branches:
      - master

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Automated Issue: Daily Check",
              body: "This issue was created automatically by GitHub Actions.\n\n- Task 1\n- Task 2",
              labels: ["automated", "triage"]
            });

      
